
name: Build Kernel on Github Actions

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: panchajanya1999/archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup env
        run: pacman -Syu --needed --noconfirm wget base-devel xmlto inetutils bc cpio python-sphinx python-sphinx_rtd_theme graphviz imagemagick git python zip github-cli fortune-mod ccache
      - name: Initialize ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: Build Stratosphere Kernel
        run: |
          bash ci_build.sh
        env:
          token: ${{ secrets.TG_TOKEN }}
      - name: Store Kernel Package as Artifact
        uses: actions/upload-artifact@v3
        with:
         name: Flashable zip
         path: AnyKernel3/package.zip
